version: "3.7"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  todaysfail-api:
    image: ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REGISTRY_NAME}:${VERSION}
    container_name: todaysfail-api
    ports:
      - "80:8080"
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul