spring:
  profiles:
    include:
      - infrastructure
      - domain
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY:secret-key}
    access-exp: ${JWT_ACCESS_EXP:3600}
    refresh-exp: ${JWT_REFRESH_EXP:3600}
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    ROOT: WARN