version: "3.7"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  todaysfail-api:
    image: ${AWS_ECR_REGISTRY}/todaysfail-api:${VERSION}
    container_name: todaysfail-api
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul